### ISSUE TITLE
String fields have a space between each character

### ISSUE THREAD

**Issue by MegaNarwhal** [ldilley/minestat#13]
### Expected behavior
The MOTD should reflect what is shown in the Minecraft multiplayer server list.
### Actual behavior/symptoms
There is a space between each character of the MOTD, as well as between each character of the version and the player count strings.
### Steps to reproduce behavior/symptoms
Ping a server (I used hivemc.eu) and check the aforementioned fields in the result.
### MineStat version
Java implementation from d08ee464f849dc9dd90cd62527c32d29c367b4fa
### Operating system
Windows

**Comment by ldilley** [comment]
I just ran a test against the same server (hivemc.eu) and this is what it yields in my shell using d08ee46:

`Minecraft server status of hivemc.eu on port 25565:
Server is online running version BeeCord 1.7.x '� 1.12.x with 3525 out of 20000 players.
Message of the day: �f�f                      �e%��6%��e%� �6�lThe �e�lHive �e%��6%��e%�`

As you can see, there are no spaces between the version (with the exception of the two versions sent by Bungeecord -- which is intended in this context), the current player count, and the max count characters. The motd is preserved from whatever the remote sends. "The" and "Hive" are cohesive as per above. What are you using to display the results? The Unicode characters contained in the above string may cause some rendering funk depending on whatever it is you are using. Of course, my fish shell isn't equipped to handle the color control codes and cool icons the Minecraft client sees prior to connecting.

**Comment by MegaNarwhal** [comment]
This is what I'm getting in the Windows command prompt window:
```
? f ? f                                             ? e%? ? 6%? ? e%?   ? 6 ? l
T h e   ? e ? l H i v e   ? e%? ? 6%? ? e%?
```

Here's what the same MOTD looks like sent as a message on Discord:
```
§f§f                      §e%Ä§6%®§e%º §6§lThe §e§lHive §e%Ä§6%®§e%º
```

The message being incorrectly displayed in both cases, and with other servers, seems to indicate that something is going wrong when parsing the server's response.

**Comment by MegaNarwhal** [comment]
Adding `System.out.println(rawServerData);` in MineStat shows the issue as well:
```
ÿ g ? 1   1 2 7   B e e C o r d   1 . 7 . x  '?   1 . 1 2 . x   ? f ? f
                                    ? e%Ä ? 6%? ? e%º   ? 6 ? l T h e   ? e ? l
H i v e   ? e%Ä ? 6%? ? e%º   3 4 4 2   2 0 0 0 0
? f ? f                                             ? e%Ä ? 6%? ? e%º   ? 6 ? l
T h e   ? e ? l H i v e   ? e%Ä ? 6%? ? e%º
```

**Comment by ldilley** [comment]
I see what you are referring to now. Those are actually not spaces, but rather NUL bytes (ASCII character 0 versus 32.) This is why the raw data is split on such characters in the following assignment:

`serverData = rawServerData.split("\u0000\u0000\u0000");`

I just attempted running the same query against the same server using the latest JDK 8 in the Windows 10 command prompt and was able to replicate your finding. Oddly, this does not show up in Linux using bash or fish. I've just committed a fix after testing the change (removal of any remaining NUL bytes in each string) in both Linux and Windows. The Linux execution presented no visual change whereas the output in the Windows command prompt now lacks the extraneous padding. Thank you for bringing this to my attention, @MegaNarwhal. Please let me know if it looks better on your end when you have a moment to test.

**Comment by ldilley** [comment]
Closing due to lack of feedback.
