### ISSUE TITLE
Is it not possible to get current players uuids?

### ISSUE THREAD

**Issue by OzanKurt** [ldilley/minestat#32]

**Comment by ldilley** [comment]
Greetings, @OzanKurt.

Apologies for the delay in responding -- it was recently Thanksgiving in the US. Unfortunately, MineStat does not currently support retrieving player names and corresponding UUIDs. #21 was created to add this feature however. The Ruby implementation currently supports all the SLP protocols up to 1.6. This includes 1.8b/1.3, 1.4/1.5, and 1.6. The server response for these versions is very basic and does not include player names or UUIDs. SLP 1.7 (the latest protocol at the time of this writing) provides a JSON response which includes the data you are looking for. When my slothfulness dissipates, I hope to finish adding support for all available protocol versions for each language implementation.

Here is some information on the SLP protocol if you are interested: https://wiki.vg/Server_List_Ping

Please let me know if you require anything else. If there is no reply within the next several days, I'll assume that you are all set and close this issue.

**Comment by OzanKurt** [comment]
Hi there,

Is there a guide where I can find how to connect to this newer version? I might be able to implement the PHP version.

**Comment by ldilley** [comment]
The link I referenced above, https://wiki.vg/Server_List_Ping, along with #21 provide the handshake/steps.
