### ISSUE TITLE
minestat.js return error instead of "not online"

### ISSUE THREAD

**Issue by ThisTNTSquid** [ldilley/minestat#8]
I found the minestat.js is behaving very weird, which when it try to query a server that is not opened (online), it will throw and error like the following (TCP connection refuse error) instead of filling `online = false`
```
{ Error: connect ECONNREFUSED 127.0.0.1:25566
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 25566 }
```

I still haven't figure out a fix to this, but maybe you should take a look of this problem

**Comment by ldilley** [comment]
Fixed in 7af0b9fbdec819cd9c551b01638b83aa560a69f0.
